kevinhlau/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

import wedding.views

# urlpatterns = [
#     url(r'^wedding/', include('wedding.urls')),
#     url(r'^admin/', admin.site.urls),
# ]

urlpatterns = [
    url(r'^$', wedding.views.index, name='index'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    
    url(r'^wedding/', include('wedding.urls')),
    url(r'^admin/', admin.site.urls),
)

wedding/urls.py
from django.conf.urls import url

from . import views

app_name = 'wedding'

urlpatterns = [
    # e.g. /wedding
    url(r'^$', views.index, name='index'),
    # e.g. /wedding/rsvp
    url(r'^rsvp/$', views.rsvp, name='rsvp'),
    url(r'^registry/$', views.registry, name='registry'),
    url(r'^accomodations/$', views.accomodations, name='accomodations'),
    url(r'^test/$', views.test, name='test'),
           
]

wedding/models.py
from django.db import models

from datetime import date

# Meal options should only be editable by admin, and is referenced by Guest model.
class Meal(models.Model):
    choice = models.CharField(max_length=200)
    description = models.CharField(max_length=500)

    def __repr__(self):
        return "<Meal(choice='%s')>" % (self.choice)

    def __str__(self):
        return self.choice

# List of guests, their relationship to Kevin or Melissa, whether they are attending, meal choice, comments, and any plus ones. Plus ones are also added to the guest list and are indicated by the added_by field.
class Guest(models.Model):
    first_name = models.CharField(max_length=100, default="")
    last_name = models.CharField(max_length=100, default="")
    email = models.EmailField(default="")
    relationship_to_wedding_party = models.CharField(max_length=200, default="")
    attending = models.NullBooleanField()
    meal = models.ForeignKey(Meal)
    comments = models.TextField(default="")
    plus_ones = models.IntegerField(default=0)
    date_created = models.DateField(default=date.today)
    added_by = models.ForeignKey("self", null=True)

    def __repr__(self):
        return "<Guest(first_name='%s', last_name='%s')>" % (self.first_name, self.last_name)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

wedding/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse

from .models import Meal, Guest

from django.utils.translation import ugettext_lazy as _, activate

from datetime import date

# Create your views here.
def index(request):
    WEDDING_DATE = date(2018, 1, 28)
    wedding_date = _("{day}, {month} {date}, {year}").format(
        day=WEDDING_DATE.strftime("%A"), 
        month=WEDDING_DATE.strftime("%B"), 
        # month2 is for chinese only
        month2=WEDDING_DATE.strftime("%-m"),
        # ##########################
        date=WEDDING_DATE.day, 
        year=WEDDING_DATE.year)
    context = {
        "wedding_date" : wedding_date,
    }
    return render(request, 'wedding/index.html', context)

def rsvp(request):
    if request.method == "POST":
        params = request.POST

        attending = params.get("attendingRadios", "")
        if attending == "yes":
            attending = True
        elif attending == "no":
            attending = False
        else:
            attending = None

        meal = params.get("meal", "")
        meal = get_object_or_404(Meal, choice__startswith=meal)

        guest = Guest(first_name=params.get("first_name", ""),
            last_name=params.get("last_name", ""),
            email=params.get("email", ""),
            attending=attending,
            meal=meal,
            relationship_to_wedding_party=params.get("relationshipRadios", ""),
            comments=params.get("comments", ""),
            )
        
        guest.save()

        return render(request, 'wedding/rsvp_complete.html')
    return render(request, 'wedding/rsvp.html')

def registry(request):
    return render(request, 'wedding/registry.html')

def accomodations(request):
    return render(request, 'wedding/accomodations.html')

def test(request):
    return render(request, 'wedding/test.html')

wedding/templates/wedding/accomodations.html
{% extends "./base.html" %}

{% load i18n %}

{% block content-title %}<h1>{% trans "Accomodations" %}</h1>{% endblock content-title %}

{% block content %}

<div class="row marketing">
    <div class="col-lg-12">
        <h4>Double Tree</h4>
        <a class="btn btn-link" role="button" href="https://goo.gl/maps/LKKYYMyFNsD2">1800 S Santan Village Pkwy, Gilbert, AZ 85295</a><br>
        <a class="btn btn-link" role="button" href="http://doubletree3.hilton.com/en/hotels/arizona/doubletree-by-hilton-hotel-phoenix-gilbert-PHXSTDT/maps-directions/index.html">Website</a>
        <h4>Hyatt Place</h4>
        <a class="btn btn-link" role="button" href="https://goo.gl/maps/wg6MFe5LVyA2">3275 S Market St, Gilbert, AZ 85297</a><br>
        <a class="btn btn-link" role="button" href="https://gilbert.place.hyatt.com/en/hotel/home.html">Website</a>
    </div>
</div>


{% endblock content %}

wedding/templates/wedding/base.html
<!DOCTYPE html>
<html lang="en">
  <head>

    {% load static %}
    {% load i18n %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/png" href="{% static 'wedding/img/favicon.png' %}"/>

    <title>{% block title %}Kevin and Melissa{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'wedding/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <link href="{% static 'wedding/css/jumbotron-narrow.css' %}" rel="stylesheet">
    <link href="{% static 'wedding/css/justified-nav.css' %}" rel="stylesheet">
    <link href="{% static 'wedding/css/styles.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar-wrapper">
      <div class="container">
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'wedding:index' %}">{% trans "Kevin and Melissa" %}</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'wedding:index' %}">{% trans "Wedding" %}</a></li>
                <li><a href="{% url 'wedding:rsvp' %}">{% trans "RSVP" %}</a></li>
                {% get_current_language as LANGUAGE_CODE %}
                {% if LANGUAGE_CODE == 'en' %}
                <li><a href="{% url 'wedding:registry' %}">{% trans "Registry" %}</a></li>
                {% endif %}
                <li><a href="{% url 'wedding:accomodations' %}">{% trans "Accomodations" %}</a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>

    {% block jumbo-picture %}{% endblock jumbo-picture %}
      
    <div class="container">
      <!-- <div class="masthead">
        <h1 class="text-muted main-title">{% trans "Kevin and Melissa" %}</h1>
      </div> -->
            
      <div class="row marketing">
        <div class="col-lg-12">
          {% block content-title %}{% endblock content-title %}
        </div>
      </div>

      {% block content %}{% endblock content %}

        <form action="{% url 'set_language' %}" method="post" style="position: fixed; right: 15px; bottom: 15px">{% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}" />
            <select name="language">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                {% endfor %}
            </select>
            <input type="submit" value="Go" />
        </form>

      <footer class="footer">
        <p>Made by Kevin</p>
      </footer>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'wedding/js/bootstrap.min.js' %}"></script>
    <script>
      $(document).ready(function() {
        $('.nav li a[href="' + this.location.pathname + '"]').parent().addClass('active');
      });
      
      $(".nav li a").on("click", function(){
        $(".nav").find(".active").removeClass("active");
        $(this).parent().addClass("active");
      });
    </script>
    {% block scripts %}{% endblock scripts %}
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
  </body>
</html>

wedding/templates/wedding/index.html
{% extends "./base.html" %}

{% load i18n %}
{% load static %}

{% block jumbo-picture %}

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static 'wedding/img/stairs.jpg' %}" alt="First slide">
          <div class="container">
            <!-- <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div> -->
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="{% static 'wedding/img/stairs_forehead.jpg' %}"" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <!-- <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p> -->
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="{% static 'wedding/img/table.jpg' %}" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <!-- <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p> -->
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
{% endblock jumbo-picture %}

        

{% block content-title %}<h1 class="main-title">{% trans "Kevin and Melissa" %}</h1>{% endblock content-title %}

{% block content %}

<div class="row marketing">
    <div class="col-lg-12">
        <h3 style="text-align: center">{% trans "Reception" %}</h3>
        <h4 id="location" style="text-align: center">{% trans "Gilbert, AZ" %}</h4>
        <h4 id="wedding_date" style="text-align: center">{{ wedding_date }}</h4>
    </div>
</div>

{% endblock content %}

wedding/templates/wedding/registry.html
{% extends "./base.html" %}

{% load i18n %}

{% block content-title %}<h1>{% trans "Registry" %}</h1>{% endblock content-title%}

{% block content %}

<div class="row marketing">
    <div class="col-lg-12">
        <p>{% trans "We just want you at our wedding!" %}</p>
        <!-- <a href="https://www.amazon.com/wedding/share/kevinmelissaweddingregistry">Amazon wedding registry</a> -->
    </div>
</div>

{% endblock content %}

wedding/templates/wedding/rsvp.html
{% extends "./base.html" %}

{% load i18n %}
{% load static %}

{% block content-title %}<h1>{% trans "RSVP" %}</h1>{% endblock content-title %}

{% block content %}
<div class="row marketing">
    <div class="col-lg-12">
        <form name="rsvp_form" method="post">
        {% csrf_token %}
            <div class="form-group">
                <!-- <label for="first_name">First name</label> -->
                <input type="text" class="form-control" id="first_name" name="first_name" placeholder="{% trans 'First name' %}">
            </div>
            {% get_current_language as LANGUAGE %}
            {% if LANGUAGE == 'en' %}
            <div class="form-group">
                <!-- <label for="last_name">Last name</label> -->
                <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last name">
            </div>
            {% endif %}
            <div class="form-group">
                <!-- <label for="email">Email</label> -->
                <input type="email" class="form-control" id="email" name="email" placeholder="{% trans 'YourEmailAddress@email.com' %}">
            </div>
            <div class="form-group">
                <label for="attending">{% trans "Will you be attending?" %}</label>
                <div class="radio">
                    <label>
                        <input type="radio" name="attendingRadios" id="attendingRadios1" value="yes">
                        {% trans 'Yes' %}
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="attendingRadios" id="attendingRadios2" value="no">
                        {% trans 'No' %}
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label for="meal">{% trans "Select meal option" %}</label>
                <select class="form-control" name="meal">
                    <option value="chicken">{% trans "Chicken" %}</option>
                    <option value="vegetarian">{% trans "Vegetarian" %}</option>
                </select>
            </div>

            <div class="form-group">
                <label for="relationship">{% trans "Relationship to wedding party" %}</label>
                <div class="radio">
                    <label>
                        <input type="radio" name="relationshipRadios" id="relationshipRadios1" value="bride">
                        {% trans "I know the bride" %}
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="relationshipRadios" id="relationshipRadios2" value="groom">
                        {% trans "I know the groom" %}
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="relationshipRadios" id="relationshipRadios3" value="friendOfBride">
                        {% trans "I'm going with someone who knows the bride" %}
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="relationshipRadios" id="relationshipRadios4" value="friendOfGroom">
                        {% trans "I'm going with someone who knows the groom" %}
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label for="comments">{% trans "Leave a comment" %}</label>
                <textarea class="form-control" id="comments" name="comments" rows="3"></textarea>
            </div>

            <button type="submit" class="btn btn-default">{% trans "Submit" %}</button>
        </form>
    </div>
</div>


{% endblock content %}

{% block scripts %}
    <!-- Get lib for jQuery validation -->
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
    <script src="{% static 'wedding/js/validation.js' %}"></script>
{% endblock scripts %}

wedding/templates/wedding/rsvp_complete.html
{% extends "./base.html" %}

{% load i18n %}

{% block content-title %}<h1>{% trans "RSVP Complete" %}</h1>{% endblock content-title %}

{% block content %}
<div class="row marketing">
    <div class="col-lg-12">
        <p>{% trans "Thank you for responding!" %}
        <a href="{% url 'wedding:index' %}">{% trans "Click here to return to home page." %}</a></p>
    </div>
</div>


{% endblock content %}

wedding/templates/wedding/test.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Navbar Template for Bootstrap</title>

    {% load static %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'wedding/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'wedding/css/navbar.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Navbar example</h1>
        <p>This example is a quick exercise to illustrate how the default, static navbar and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>
          <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
        </p>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'wedding/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>